/*
 * Copyright 2019 Institut Laue–Langevin
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.thomsonreuters.wokmws.v3.woksearch;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WokSearch", targetNamespace = "http://woksearch.v3.wokmws.thomsonreuters.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WokSearch {


    /**
     * 
     * @param retrieveParameters
     * @param queryId
     * @return
     *     returns java.util.List<com.thomsonreuters.wokmws.v3.woksearch.CitedReference>
     * @throws InvalidInputException_Exception
     * @throws QueryException_Exception
     * @throws AuthenticationException_Exception
     * @throws InternalServerException_Exception
     * @throws SessionException_Exception
     * @throws ESTIWSException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "citedReferencesRetrieve", targetNamespace = "http://woksearch.v3.wokmws.thomsonreuters.com", className = "com.thomsonreuters.wokmws.v3.woksearch.CitedReferencesRetrieve")
    @ResponseWrapper(localName = "citedReferencesRetrieveResponse", targetNamespace = "http://woksearch.v3.wokmws.thomsonreuters.com", className = "com.thomsonreuters.wokmws.v3.woksearch.CitedReferencesRetrieveResponse")
    public List<CitedReference> citedReferencesRetrieve(
			@WebParam(name = "queryId", targetNamespace = "")
					String queryId,
			@WebParam(name = "retrieveParameters", targetNamespace = "")
					RetrieveParameters retrieveParameters)
        throws AuthenticationException_Exception, ESTIWSException_Exception, InternalServerException_Exception, InvalidInputException_Exception, QueryException_Exception, SessionException_Exception
    ;

    /**
     * 
     * @param uid
     * @param editions
     * @param timeSpan
     * @param queryLanguage
     * @param databaseId
     * @param retrieveParameters
     * @return
     *     returns com.thomsonreuters.wokmws.v3.woksearch.FullRecordSearchResults
     * @throws InvalidInputException_Exception
     * @throws QueryException_Exception
     * @throws AuthenticationException_Exception
     * @throws InternalServerException_Exception
     * @throws SessionException_Exception
     * @throws ESTIWSException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "relatedRecords", targetNamespace = "http://woksearch.v3.wokmws.thomsonreuters.com", className = "com.thomsonreuters.wokmws.v3.woksearch.RelatedRecords")
    @ResponseWrapper(localName = "relatedRecordsResponse", targetNamespace = "http://woksearch.v3.wokmws.thomsonreuters.com", className = "com.thomsonreuters.wokmws.v3.woksearch.RelatedRecordsResponse")
    public FullRecordSearchResults relatedRecords(
			@WebParam(name = "databaseId", targetNamespace = "")
					String databaseId,
			@WebParam(name = "uid", targetNamespace = "")
					String uid,
			@WebParam(name = "editions", targetNamespace = "")
					List<EditionDesc> editions,
			@WebParam(name = "timeSpan", targetNamespace = "")
					TimeSpan timeSpan,
			@WebParam(name = "queryLanguage", targetNamespace = "")
					String queryLanguage,
			@WebParam(name = "retrieveParameters", targetNamespace = "")
					RetrieveParameters retrieveParameters)
        throws AuthenticationException_Exception, ESTIWSException_Exception, InternalServerException_Exception, InvalidInputException_Exception, QueryException_Exception, SessionException_Exception
    ;

    /**
     * 
     * @param uid
     * @param queryLanguage
     * @param databaseId
     * @param retrieveParameters
     * @return
     *     returns com.thomsonreuters.wokmws.v3.woksearch.CitedReferencesSearchResults
     * @throws InvalidInputException_Exception
     * @throws QueryException_Exception
     * @throws AuthenticationException_Exception
     * @throws InternalServerException_Exception
     * @throws SessionException_Exception
     * @throws ESTIWSException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "citedReferences", targetNamespace = "http://woksearch.v3.wokmws.thomsonreuters.com", className = "com.thomsonreuters.wokmws.v3.woksearch.CitedReferences")
    @ResponseWrapper(localName = "citedReferencesResponse", targetNamespace = "http://woksearch.v3.wokmws.thomsonreuters.com", className = "com.thomsonreuters.wokmws.v3.woksearch.CitedReferencesResponse")
    public CitedReferencesSearchResults citedReferences(
			@WebParam(name = "databaseId", targetNamespace = "")
					String databaseId,
			@WebParam(name = "uid", targetNamespace = "")
					String uid,
			@WebParam(name = "queryLanguage", targetNamespace = "")
					String queryLanguage,
			@WebParam(name = "retrieveParameters", targetNamespace = "")
					RetrieveParameters retrieveParameters)
        throws AuthenticationException_Exception, ESTIWSException_Exception, InternalServerException_Exception, InvalidInputException_Exception, QueryException_Exception, SessionException_Exception
    ;

    /**
     * 
     * @param retrieveParameters
     * @param queryId
     * @return
     *     returns com.thomsonreuters.wokmws.v3.woksearch.FullRecordData
     * @throws InvalidInputException_Exception
     * @throws QueryException_Exception
     * @throws AuthenticationException_Exception
     * @throws InternalServerException_Exception
     * @throws SessionException_Exception
     * @throws ESTIWSException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "retrieve", targetNamespace = "http://woksearch.v3.wokmws.thomsonreuters.com", className = "com.thomsonreuters.wokmws.v3.woksearch.Retrieve")
    @ResponseWrapper(localName = "retrieveResponse", targetNamespace = "http://woksearch.v3.wokmws.thomsonreuters.com", className = "com.thomsonreuters.wokmws.v3.woksearch.RetrieveResponse")
    public FullRecordData retrieve(
			@WebParam(name = "queryId", targetNamespace = "")
					String queryId,
			@WebParam(name = "retrieveParameters", targetNamespace = "")
					RetrieveParameters retrieveParameters)
        throws AuthenticationException_Exception, ESTIWSException_Exception, InternalServerException_Exception, InvalidInputException_Exception, QueryException_Exception, SessionException_Exception
    ;

    /**
     * 
     * @param queryParameters
     * @param retrieveParameters
     * @return
     *     returns com.thomsonreuters.wokmws.v3.woksearch.FullRecordSearchResults
     * @throws InvalidInputException_Exception
     * @throws QueryException_Exception
     * @throws AuthenticationException_Exception
     * @throws InternalServerException_Exception
     * @throws SessionException_Exception
     * @throws ESTIWSException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "search", targetNamespace = "http://woksearch.v3.wokmws.thomsonreuters.com", className = "com.thomsonreuters.wokmws.v3.woksearch.Search")
    @ResponseWrapper(localName = "searchResponse", targetNamespace = "http://woksearch.v3.wokmws.thomsonreuters.com", className = "com.thomsonreuters.wokmws.v3.woksearch.SearchResponse")
    public FullRecordSearchResults search(
			@WebParam(name = "queryParameters", targetNamespace = "")
					QueryParameters queryParameters,
			@WebParam(name = "retrieveParameters", targetNamespace = "")
					RetrieveParameters retrieveParameters)
        throws AuthenticationException_Exception, ESTIWSException_Exception, InternalServerException_Exception, InvalidInputException_Exception, QueryException_Exception, SessionException_Exception
    ;

    /**
     * 
     * @param uid
     * @param editions
     * @param timeSpan
     * @param queryLanguage
     * @param databaseId
     * @param retrieveParameters
     * @return
     *     returns com.thomsonreuters.wokmws.v3.woksearch.FullRecordSearchResults
     * @throws InvalidInputException_Exception
     * @throws QueryException_Exception
     * @throws AuthenticationException_Exception
     * @throws InternalServerException_Exception
     * @throws SessionException_Exception
     * @throws ESTIWSException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "citingArticles", targetNamespace = "http://woksearch.v3.wokmws.thomsonreuters.com", className = "com.thomsonreuters.wokmws.v3.woksearch.CitingArticles")
    @ResponseWrapper(localName = "citingArticlesResponse", targetNamespace = "http://woksearch.v3.wokmws.thomsonreuters.com", className = "com.thomsonreuters.wokmws.v3.woksearch.CitingArticlesResponse")
    public FullRecordSearchResults citingArticles(
			@WebParam(name = "databaseId", targetNamespace = "")
					String databaseId,
			@WebParam(name = "uid", targetNamespace = "")
					String uid,
			@WebParam(name = "editions", targetNamespace = "")
					List<EditionDesc> editions,
			@WebParam(name = "timeSpan", targetNamespace = "")
					TimeSpan timeSpan,
			@WebParam(name = "queryLanguage", targetNamespace = "")
					String queryLanguage,
			@WebParam(name = "retrieveParameters", targetNamespace = "")
					RetrieveParameters retrieveParameters)
        throws AuthenticationException_Exception, ESTIWSException_Exception, InternalServerException_Exception, InvalidInputException_Exception, QueryException_Exception, SessionException_Exception
    ;

    /**
     * 
     * @param uid
     * @param queryLanguage
     * @param databaseId
     * @param retrieveParameters
     * @return
     *     returns com.thomsonreuters.wokmws.v3.woksearch.FullRecordSearchResults
     * @throws InvalidInputException_Exception
     * @throws QueryException_Exception
     * @throws AuthenticationException_Exception
     * @throws InternalServerException_Exception
     * @throws SessionException_Exception
     * @throws ESTIWSException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "retrieveById", targetNamespace = "http://woksearch.v3.wokmws.thomsonreuters.com", className = "com.thomsonreuters.wokmws.v3.woksearch.RetrieveById")
    @ResponseWrapper(localName = "retrieveByIdResponse", targetNamespace = "http://woksearch.v3.wokmws.thomsonreuters.com", className = "com.thomsonreuters.wokmws.v3.woksearch.RetrieveByIdResponse")
    public FullRecordSearchResults retrieveById(
			@WebParam(name = "databaseId", targetNamespace = "")
					String databaseId,
			@WebParam(name = "uid", targetNamespace = "")
					List<String> uid,
			@WebParam(name = "queryLanguage", targetNamespace = "")
					String queryLanguage,
			@WebParam(name = "retrieveParameters", targetNamespace = "")
					RetrieveParameters retrieveParameters)
        throws AuthenticationException_Exception, ESTIWSException_Exception, InternalServerException_Exception, InvalidInputException_Exception, QueryException_Exception, SessionException_Exception
    ;

}
